### ISSUE TITLE
Tenant and endpoint creation fails if [TENANT|ENDPOINT]_RESOURCES not set

### ISSUE THREAD

**Issue by poussa** [IntelAI/inference-model-manager#92]
The default [TENANT|ENDPOINT]_RESOURCES settings in imm script creates invalid json which fails to create the tenant or endpoint resource. 

https://github.com/IntelAI/inference-model-manager/blob/master/scripts/imm#L127
https://github.com/IntelAI/inference-model-manager/blob/master/scripts/imm#L129

Both have extra `}` at the end.

Steps to reproduce
$ unset ENDPOINT_RESOURCES
$ ./imm create e ep-1 resnet [enter]
Please provide model version policy (press enter for default)
Please provide tenant name default-tenant
Please provide serving name (default: tf-serving)
`{"title": "Unexpected error occurred: ('Invalid JSON', 'Could not parse JSON body - Extra data: line 1 column 171 (char 170)')"}`

Extra data is the extra bracket `}`

**Comment by pawel-pieniazek** [comment]
As far as we checked, above lines are ok. We also couldn't reproduce this. Feel free to reopen if problem occurs again.
